apiVersion: v2
name: oci-prometheus-sd-proxy
description: Prometheus HTTP Service Discovery proxy for Oracle Cloud Infrastructure compute instances.
type: application
version: 1.0.0-rc.1
appVersion: "1.5.5"
home: https://github.com/amaanax86/oci-prometheus-sd-proxy
sources:
  - https://github.com/amaanax86/oci-prometheus-sd-proxy
maintainers:
  - name: Amaan Ul Haq Siddiqui
    email: amaanulhaq.s@outlook.com
    url: https://github.com/amaanax86
keywords:
  - prometheus
  - service-discovery
  - oci
  - oracle-cloud
  - monitoring
annotations:
  artifacthub.io/license: Apache-2.0
