apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oci-prometheus-sd-proxy.fullname" . }}
  labels:
    {{- include "oci-prometheus-sd-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oci-prometheus-sd-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oci-prometheus-sd-proxy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "oci-prometheus-sd-proxy.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: CONFIG_PATH
              value: {{ .Values.configPath | quote }}
            - name: SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.serverTokenSecret.name | quote }}
                  key: {{ .Values.serverTokenSecret.key | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: {{ .Values.configPath | quote }}
              subPath: config.yaml
              readOnly: true
            - name: oci-private-key
              mountPath: {{ printf "%s/%s" .Values.ociPrivateKeyMountPath .Values.ociPrivateKeySecret.key | quote }}
              subPath: {{ .Values.ociPrivateKeySecret.key | quote }}
              readOnly: true
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "oci-prometheus-sd-proxy.fullname" . }}
        - name: oci-private-key
          secret:
            secretName: {{ .Values.ociPrivateKeySecret.name | quote }}
